class_name KeyboardKeyList extends Node

enum FullKeyList {
	KEY_ESCAPE = 16777217,
	KEY_TAB = 16777218,
	KEY_BACKTAB = 16777219,
	KEY_BACKSPACE = 4194308,
	KEY_ENTER = 4194310,
	KEY_KP_ENTER = 16777222,
	KEY_INSERT = 16777223,
	KEY_DELETE = 16777224,
	KEY_PAUSE = 16777225,
	KEY_PRINT = 16777226,
	KEY_SYSREQ = 16777227,
	KEY_CLEAR = 16777228,
	KEY_HOME = 16777229,
	KEY_END = 16777230,
	KEY_LEFT = 4194319,
	KEY_UP = 16777232,
	KEY_RIGHT = 4194321,
	KEY_DOWN = 16777234,
	KEY_PAGEUP = 16777235,
	KEY_PAGEDOWN = 16777236,
	KEY_SHIFT = 16777237,
	KEY_CONTROL = 16777238,
	KEY_META = 16777239,
	KEY_ALT = 16777240,
	KEY_CAPSLOCK = 16777241,
	KEY_NUMLOCK = 16777242,
	KEY_SCROLLLOCK = 16777243,
	KEY_F1 = 16777244,
	KEY_F2 = 16777245,
	KEY_F3 = 16777246,
	KEY_F4 = 16777247,
	KEY_F5 = 16777248,
	KEY_F6 = 16777249,
	KEY_F7 = 16777250,
	KEY_F8 = 16777251,
	KEY_F9 = 16777252,
	KEY_F10 = 16777253,
	KEY_F11 = 16777254,
	KEY_F12 = 16777255,
	KEY_F13 = 16777256,
	KEY_F14 = 16777257,
	KEY_F15 = 16777258,
	KEY_F16 = 16777259,
	KEY_KP_MULTIPLY = 16777345,
	KEY_KP_DIVIDE = 16777346,
	KEY_KP_SUBTRACT = 16777347,
	KEY_KP_PERIOD = 16777348,
	KEY_KP_ADD = 16777349,
	KEY_KP_0 = 16777350,
	KEY_KP_1 = 16777351,
	KEY_KP_2 = 16777352,
	KEY_KP_3 = 16777353,
	KEY_KP_4 = 16777354,
	KEY_KP_5 = 16777355,
	KEY_KP_6 = 16777356,
	KEY_KP_7 = 16777357,
	KEY_KP_8 = 16777358,
	KEY_KP_9 = 16777359,
	KEY_SUPER_L = 16777260,
	KEY_SUPER_R = 16777261,
	KEY_MENU = 16777262,
	KEY_HYPER_L = 16777263,
	KEY_HYPER_R = 16777264,
	KEY_HELP = 16777265,
	KEY_DIRECTION_L = 16777266,
	KEY_DIRECTION_R = 16777267,
	KEY_BACK = 16777280,
	KEY_FORWARD = 16777281,
	KEY_STOP = 16777282,
	KEY_REFRESH = 16777283,
	KEY_VOLUMEDOWN = 16777284,
	KEY_VOLUMEMUTE = 16777285,
	KEY_VOLUMEUP = 16777286,
	KEY_BASSBOOST = 16777287,
	KEY_BASSUP = 16777288,
	KEY_BASSDOWN = 16777289,
	KEY_TREBLEUP = 16777290,
	KEY_TREBLEDOWN = 16777291,
	KEY_MEDIAPLAY = 16777292,
	KEY_MEDIASTOP = 16777293,
	KEY_MEDIAPREVIOUS = 16777294,
	KEY_MEDIANEXT = 16777295,
	KEY_MEDIARECORD = 16777296,
	KEY_HOMEPAGE = 16777297,
	KEY_FAVORITES = 16777298,
	KEY_SEARCH = 16777299,
	KEY_STANDBY = 16777300,
	KEY_OPENURL = 16777301,
	KEY_LAUNCHMAIL = 16777302,
	KEY_LAUNCHMEDIA = 16777303,
	KEY_LAUNCH0 = 16777304,
	KEY_LAUNCH1 = 16777305,
	KEY_LAUNCH2 = 16777306,
	KEY_LAUNCH3 = 16777307,
	KEY_LAUNCH4 = 16777308,
	KEY_LAUNCH5 = 16777309,
	KEY_LAUNCH6 = 16777310,
	KEY_LAUNCH7 = 16777311,
	KEY_LAUNCH8 = 16777312,
	KEY_LAUNCH9 = 16777313,
	KEY_LAUNCHA = 16777314,
	KEY_LAUNCHB = 16777315,
	KEY_LAUNCHC = 16777316,
	KEY_LAUNCHD = 16777317,
	KEY_LAUNCHE = 16777318,
	KEY_LAUNCHF = 16777319,
	KEY_UNKNOWN = 33554431,
	KEY_SPACE = 32,
	KEY_EXCLAM = 33,
	KEY_QUOTEDBL = 34,
	KEY_NUMBERSIGN = 35,
	KEY_DOLLAR = 36,
	KEY_PERCENT = 37,
	KEY_AMPERSAND = 38,
	KEY_APOSTROPHE = 39,
	KEY_PARENLEFT = 40,
	KEY_PARENRIGHT = 41,
	KEY_ASTERISK = 42,
	KEY_PLUS = 43,
	KEY_COMMA = 44,
	KEY_MINUS = 45,
	KEY_PERIOD = 46,
	KEY_SLASH = 47,
	KEY_0 = 48,
	KEY_1 = 49,
	KEY_2 = 50,
	KEY_3 = 51,
	KEY_4 = 52,
	KEY_5 = 53,
	KEY_6 = 54,
	KEY_7 = 55,
	KEY_8 = 56,
	KEY_9 = 57,
	KEY_COLON = 58,
	KEY_SEMICOLON = 59,
	KEY_LESS = 60,
	KEY_EQUAL = 61,
	KEY_GREATER = 62,
	KEY_QUESTION = 63,
	KEY_AT = 64,
	KEY_A = 65,
	KEY_B = 66,
	KEY_C = 67,
	KEY_D = 68,
	KEY_E = 69,
	KEY_F = 70,
	KEY_G = 71,
	KEY_H = 72,
	KEY_I = 73,
	KEY_J = 74,
	KEY_K = 75,
	KEY_L = 76,
	KEY_M = 77,
	KEY_N = 78,
	KEY_O = 79,
	KEY_P = 80,
	KEY_Q = 81,
	KEY_R = 82,
	KEY_S = 83,
	KEY_T = 84,
	KEY_U = 85,
	KEY_V = 86,
	KEY_W = 87,
	KEY_X = 88,
	KEY_Y = 89,
	KEY_Z = 90,
	KEY_BRACKETLEFT = 91,
	KEY_BACKSLASH = 92,
	KEY_BRACKETRIGHT = 93,
	KEY_ASCIICIRCUM = 94,
	KEY_UNDERSCORE = 95,
	KEY_QUOTELEFT = 96,
	KEY_BRACELEFT = 123,
	KEY_BAR = 124,
	KEY_BRACERIGHT = 125,
	KEY_ASCIITILDE = 126,
	KEY_NOBREAKSPACE = 160,
	KEY_EXCLAMDOWN = 161,
	KEY_CENT = 162,
	KEY_STERLING = 163,
	KEY_CURRENCY = 164,
	KEY_YEN = 165,
	KEY_BROKENBAR = 166,
	KEY_SECTION = 167,
	KEY_DIAERESIS = 168,
	KEY_COPYRIGHT = 169,
	KEY_ORDFEMININE = 170,
	KEY_GUILLEMOTLEFT = 171,
	KEY_NOTSIGN = 172,
	KEY_HYPHEN = 173,
	KEY_REGISTERED = 174,
	KEY_MACRON = 175,
	KEY_DEGREE = 176,
	KEY_PLUSMINUS = 177,
	KEY_TWOSUPERIOR = 178,
	KEY_THREESUPERIOR = 179,
	KEY_ACUTE = 180,
	KEY_MU = 181,
	KEY_PARAGRAPH = 182,
	KEY_PERIODCENTERED = 183,
	KEY_CEDILLA = 184,
	KEY_ONESUPERIOR = 185,
	KEY_MASCULINE = 186,
	KEY_GUILLEMOTRIGHT = 187,
	KEY_ONEQUARTER = 188,
	KEY_ONEHALF = 189,
	KEY_THREEQUARTERS = 190,
	KEY_QUESTIONDOWN = 191,
	KEY_AGRAVE = 192,
	KEY_AACUTE = 193,
	KEY_ACIRCUMFLEX = 194,
	KEY_ATILDE = 195,
	KEY_ADIAERESIS = 196,
	KEY_ARING = 197,
	KEY_AE = 198,
	KEY_CCEDILLA = 199,
	KEY_EGRAVE = 200,
	KEY_EACUTE = 201,
	KEY_ECIRCUMFLEX = 202,
	KEY_EDIAERESIS = 203,
	KEY_IGRAVE = 204,
	KEY_IACUTE = 205,
	KEY_ICIRCUMFLEX = 206,
	KEY_IDIAERESIS = 207,
	KEY_ETH = 208,
	KEY_NTILDE = 209,
	KEY_OGRAVE = 210,
	KEY_OACUTE = 211,
	KEY_OCIRCUMFLEX = 212,
	KEY_OTILDE = 213,
	KEY_ODIAERESIS = 214,
	KEY_MULTIPLY = 215,
	KEY_OOBLIQUE = 216,
	KEY_UGRAVE = 217,
	KEY_UACUTE = 218,
	KEY_UCIRCUMFLEX = 219,
	KEY_UDIAERESIS = 220,
	KEY_YACUTE = 221,
	KEY_THORN = 222,
	KEY_SSHARP = 223,
	KEY_DIVISION = 247,
	KEY_YDIAERESIS = 255
}

var keyListLowercase = {
	"A":FullKeyList.KEY_A,
	"B":FullKeyList.KEY_B,
	"C":FullKeyList.KEY_C,
	"D":FullKeyList.KEY_D,
	"E":FullKeyList.KEY_E,
	"F":FullKeyList.KEY_F,
	"G":FullKeyList.KEY_G,
	"H":FullKeyList.KEY_H,
	"I":FullKeyList.KEY_I,
	"J":FullKeyList.KEY_J,
	"K":FullKeyList.KEY_K,
	"L":FullKeyList.KEY_L,
	"M":FullKeyList.KEY_M,
	"N":FullKeyList.KEY_N,
	"O":FullKeyList.KEY_O,
	"P":FullKeyList.KEY_P,
	"Q":FullKeyList.KEY_Q,
	"R":FullKeyList.KEY_R,
	"S":FullKeyList.KEY_S,
	"T":FullKeyList.KEY_T,
	"U":FullKeyList.KEY_U,
	"V":FullKeyList.KEY_V,
	"W":FullKeyList.KEY_W,
	"X":FullKeyList.KEY_X,
	"Y":FullKeyList.KEY_Y,
	"Z":FullKeyList.KEY_Z,
	"à":FullKeyList.KEY_AGRAVE,
	"á":FullKeyList.KEY_AACUTE,
	"â":FullKeyList.KEY_ACIRCUMFLEX,
	"ã":FullKeyList.KEY_ATILDE,
	"ä":196,
	"å":FullKeyList.KEY_ARING,
	"æ":FullKeyList.KEY_AE,
	"ç":FullKeyList.KEY_CCEDILLA,
	"è":FullKeyList.KEY_EGRAVE,
	"é":FullKeyList.KEY_EACUTE,
	"ê":FullKeyList.KEY_ECIRCUMFLEX,
	"ë":FullKeyList.KEY_EDIAERESIS,
	"ì":FullKeyList.KEY_IGRAVE,
	"í":FullKeyList.KEY_IACUTE,
	"î":FullKeyList.KEY_ICIRCUMFLEX,
	"ð":FullKeyList.KEY_ETH,
	"ñ":FullKeyList.KEY_NTILDE,
	"ò":FullKeyList.KEY_OGRAVE,
	"ó":FullKeyList.KEY_OACUTE,
	"ô":FullKeyList.KEY_OCIRCUMFLEX,
	"õ":FullKeyList.KEY_OTILDE,
	"ö":214,
	"ø":FullKeyList.KEY_OOBLIQUE,
	"ù":FullKeyList.KEY_UGRAVE,
	"ú":FullKeyList.KEY_UACUTE,
	"û":FullKeyList.KEY_UCIRCUMFLEX,
	"ü":220,
	"ý":FullKeyList.KEY_YACUTE,
	"ÿ":FullKeyList.KEY_YDIAERESIS,
}

var keyListUnicode = {
	"Escape":FullKeyList.KEY_ESCAPE,
	"Tab":FullKeyList.KEY_TAB,
	"Shift-Tab":FullKeyList.KEY_BACKTAB,
	"Backspace":FullKeyList.KEY_BACKSPACE,
	"Return":FullKeyList.KEY_ENTER,
	"Enter":FullKeyList.KEY_KP_ENTER,
	"Insert":FullKeyList.KEY_INSERT,
	"Delete":FullKeyList.KEY_DELETE,
	"Pause":FullKeyList.KEY_PAUSE,
	"Printscreen":FullKeyList.KEY_PRINT,
	"SystemRequest":FullKeyList.KEY_SYSREQ,
	"Clear":FullKeyList.KEY_CLEAR,
	"Home":FullKeyList.KEY_HOME,
	"End":FullKeyList.KEY_END,
	"LeftArrow":FullKeyList.KEY_LEFT,
	"UpArrow":FullKeyList.KEY_UP,
	"RightArrow":FullKeyList.KEY_RIGHT,
	"DownArrow":FullKeyList.KEY_DOWN,
	"Pageup":FullKeyList.KEY_PAGEUP,
	"Pagedown":FullKeyList.KEY_PAGEDOWN,
	"Shift":FullKeyList.KEY_SHIFT,
	"Control":KEY_CTRL,
	"Meta":KEY_META,
	"Alt":KEY_ALT,
	"Capslock":FullKeyList.KEY_CAPSLOCK,
	"Numlock":FullKeyList.KEY_NUMLOCK,
	"Scrolllock":FullKeyList.KEY_SCROLLLOCK,
	"F1":FullKeyList.KEY_F1,
	"F2":FullKeyList.KEY_F2,
	"F3":FullKeyList.KEY_F3,
	"F4":FullKeyList.KEY_F4,
	"F5":FullKeyList.KEY_F5,
	"F6":FullKeyList.KEY_F6,
	"F7":FullKeyList.KEY_F7,
	"F8":FullKeyList.KEY_F8,
	"F9":FullKeyList.KEY_F9,
	"F10":FullKeyList.KEY_F10,
	"F11":FullKeyList.KEY_F11,
	"F12":FullKeyList.KEY_F12,
	"F13":FullKeyList.KEY_F13,
	"F14":FullKeyList.KEY_F14,
	"F15":FullKeyList.KEY_F15,
	"F16":FullKeyList.KEY_F16,
	"MultiplyonNumpad":FullKeyList.KEY_KP_MULTIPLY,
	"DivideonNumpad":FullKeyList.KEY_KP_DIVIDE,
	"SubtractonNumpad":FullKeyList.KEY_KP_SUBTRACT,
	"PeriodonNumpad":FullKeyList.KEY_KP_PERIOD,
	"AddonNumpad":FullKeyList.KEY_KP_ADD,
	"Number0onNumpad":FullKeyList.KEY_KP_0,
	"Number1onNumpad":FullKeyList.KEY_KP_1,
	"Number2onNumpad":FullKeyList.KEY_KP_2,
	"Number3onNumpad":FullKeyList.KEY_KP_3,
	"Number4onNumpad":FullKeyList.KEY_KP_4,
	"Number5onNumpad":FullKeyList.KEY_KP_5,
	"Number6onNumpad":FullKeyList.KEY_KP_6,
	"Number7onNumpad":FullKeyList.KEY_KP_7,
	"Number8onNumpad":FullKeyList.KEY_KP_8,
	"Number9onNumpad":FullKeyList.KEY_KP_9,
	"LeftSuper(Windows)":FullKeyList.KEY_MENU,
	"LeftHyper":FullKeyList.KEY_HYPER_L,
	"RightHyper":FullKeyList.KEY_HYPER_R,
	"Help":FullKeyList.KEY_HELP,
	"LeftDirection":FullKeyList.KEY_DIRECTION_L,
	"RightDirection":FullKeyList.KEY_DIRECTION_R,
	"Back":FullKeyList.KEY_BACK,
	"Forward":FullKeyList.KEY_FORWARD,
	"Stop":FullKeyList.KEY_STOP,
	"Refresh":FullKeyList.KEY_REFRESH,
	"Volumedown":FullKeyList.KEY_VOLUMEDOWN,
	"Mutevolume":FullKeyList.KEY_VOLUMEMUTE,
	"Volumeup":FullKeyList.KEY_VOLUMEUP,
	"BassBoost":FullKeyList.KEY_BASSBOOST,
	"BassUp":FullKeyList.KEY_BASSUP,
	"BassDown":FullKeyList.KEY_BASSDOWN,
	"TrebleUp":FullKeyList.KEY_TREBLEUP,
	"TrebleDown":FullKeyList.KEY_TREBLEDOWN,
	"Mediaplay":FullKeyList.KEY_MEDIAPLAY,
	"Mediastop":FullKeyList.KEY_MEDIASTOP,
	"Previoussong":FullKeyList.KEY_MEDIAPREVIOUS,
	"Nextsong":FullKeyList.KEY_MEDIANEXT,
	"Mediarecord":FullKeyList.KEY_MEDIARECORD,
	"Homepage":FullKeyList.KEY_HOMEPAGE,
	"Favorites":FullKeyList.KEY_FAVORITES,
	"Search":FullKeyList.KEY_SEARCH,
	"Standby":FullKeyList.KEY_STANDBY,
	"OpenURL/LaunchBrowser":FullKeyList.KEY_OPENURL,
	"LaunchMail":FullKeyList.KEY_LAUNCHMAIL,
	"LaunchMedia":FullKeyList.KEY_LAUNCHMEDIA,
	"LaunchShortcut0":FullKeyList.KEY_LAUNCH0,
	"LaunchShortcut1":FullKeyList.KEY_LAUNCH1,
	"LaunchShortcut2":FullKeyList.KEY_LAUNCH2,
	"LaunchShortcut3":FullKeyList.KEY_LAUNCH3,
	"LaunchShortcut4":FullKeyList.KEY_LAUNCH4,
	"LaunchShortcut5":FullKeyList.KEY_LAUNCH5,
	"LaunchShortcut6":FullKeyList.KEY_LAUNCH6,
	"LaunchShortcut7":FullKeyList.KEY_LAUNCH7,
	"LaunchShortcut8":FullKeyList.KEY_LAUNCH8,
	"LaunchShortcut9":FullKeyList.KEY_LAUNCH9,
	"LaunchShortcutA":FullKeyList.KEY_LAUNCHA,
	"LaunchShortcutB":FullKeyList.KEY_LAUNCHB,
	"LaunchShortcutC":FullKeyList.KEY_LAUNCHC,
	"LaunchShortcutD":FullKeyList.KEY_LAUNCHD,
	"LaunchShortcutE":FullKeyList.KEY_LAUNCHE,
	"LaunchShortcutF":FullKeyList.KEY_LAUNCHF,
	"Unknown":FullKeyList.KEY_UNKNOWN,
	"Space":FullKeyList.KEY_SPACE,
	"!":FullKeyList.KEY_EXCLAM,
	"\"":FullKeyList.KEY_QUOTEDBL,
	"#":FullKeyList.KEY_NUMBERSIGN,
	"$":FullKeyList.KEY_DOLLAR,
	"%":FullKeyList.KEY_PERCENT,
	"&":FullKeyList.KEY_AMPERSAND,
	"'":FullKeyList.KEY_APOSTROPHE,
	"(":FullKeyList.KEY_PARENLEFT,
	")":FullKeyList.KEY_PARENRIGHT,
	"*":FullKeyList.KEY_ASTERISK,
	"+":FullKeyList.KEY_PLUS,
	",":FullKeyList.KEY_COMMA,
	"-":FullKeyList.KEY_MINUS,
	".":FullKeyList.KEY_PERIOD,
	"/":FullKeyList.KEY_SLASH,
	"0":FullKeyList.KEY_0,
	"1":FullKeyList.KEY_1,
	"2":FullKeyList.KEY_2,
	"3":FullKeyList.KEY_3,
	"4":FullKeyList.KEY_4,
	"5":FullKeyList.KEY_5,
	"6":FullKeyList.KEY_6,
	"7":FullKeyList.KEY_7,
	"8":FullKeyList.KEY_8,
	"9":FullKeyList.KEY_9,
	":":FullKeyList.KEY_COLON,
	";":FullKeyList.KEY_SEMICOLON,
	"<":FullKeyList.KEY_LESS,
	"=":FullKeyList.KEY_EQUAL,
	">":FullKeyList.KEY_GREATER,
	"?":FullKeyList.KEY_QUESTION,
	"@":FullKeyList.KEY_AT,
	"A":FullKeyList.KEY_A,
	"B":FullKeyList.KEY_B,
	"C":FullKeyList.KEY_C,
	"D":FullKeyList.KEY_D,
	"E":FullKeyList.KEY_E,
	"F":FullKeyList.KEY_F,
	"G":FullKeyList.KEY_G,
	"H":FullKeyList.KEY_H,
	"I":FullKeyList.KEY_I,
	"J":FullKeyList.KEY_J,
	"K":FullKeyList.KEY_K,
	"L":FullKeyList.KEY_L,
	"M":FullKeyList.KEY_M,
	"N":FullKeyList.KEY_N,
	"O":FullKeyList.KEY_O,
	"P":FullKeyList.KEY_P,
	"Q":FullKeyList.KEY_Q,
	"R":FullKeyList.KEY_R,
	"S":FullKeyList.KEY_S,
	"T":FullKeyList.KEY_T,
	"U":FullKeyList.KEY_U,
	"V":FullKeyList.KEY_V,
	"W":FullKeyList.KEY_W,
	"X":FullKeyList.KEY_X,
	"Y":FullKeyList.KEY_Y,
	"Z":FullKeyList.KEY_Z,
	"[":FullKeyList.KEY_BRACKETLEFT,
	"\\":FullKeyList.KEY_BACKSLASH,
	"]":FullKeyList.KEY_BRACKETRIGHT,
	"^":FullKeyList.KEY_ASCIICIRCUM,
	"_":FullKeyList.KEY_UNDERSCORE,
	"LeftQuote":FullKeyList.KEY_QUOTELEFT,
	"{":FullKeyList.KEY_BRACELEFT,
	"|":FullKeyList.KEY_BAR,
	"}":FullKeyList.KEY_BRACERIGHT,
	"~":FullKeyList.KEY_ASCIITILDE,
	"NoBreakSpace":FullKeyList.KEY_NOBREAKSPACE,
	"ExcalmDown":FullKeyList.KEY_EXCLAMDOWN,
	"¢":FullKeyList.KEY_CENT,
	"Sterling":FullKeyList.KEY_STERLING,
	"Currency":FullKeyList.KEY_CURRENCY,
	"Yen":FullKeyList.KEY_YEN,
	"¦":FullKeyList.KEY_BROKENBAR,
	"§":FullKeyList.KEY_SECTION,
	"¨":FullKeyList.KEY_DIAERESIS,
	"©":FullKeyList.KEY_COPYRIGHT,
	"Feminine":FullKeyList.KEY_ORDFEMININE,
	"«":FullKeyList.KEY_GUILLEMOTLEFT,
	"»":FullKeyList.KEY_NOTSIGN,
	"‐":FullKeyList.KEY_HYPHEN,
	"®":FullKeyList.KEY_REGISTERED,
	"Macron":FullKeyList.KEY_MACRON,
	"°":FullKeyList.KEY_DEGREE,
	"±":FullKeyList.KEY_PLUSMINUS,
	"²":FullKeyList.KEY_TWOSUPERIOR,
	"³":FullKeyList.KEY_THREESUPERIOR,
	"´":FullKeyList.KEY_ACUTE,
	"µ":FullKeyList.KEY_MU,
	"Paragraph":FullKeyList.KEY_PARAGRAPH,
	"·":FullKeyList.KEY_PERIODCENTERED,
	"¬":FullKeyList.KEY_CEDILLA,
	"¹":FullKeyList.KEY_ONESUPERIOR,
	"♂":FullKeyList.KEY_MASCULINE,
	"GuillemotRight":FullKeyList.KEY_GUILLEMOTRIGHT,
	"¼":FullKeyList.KEY_ONEQUARTER,
	"½":FullKeyList.KEY_ONEHALF,
	"¾":FullKeyList.KEY_THREEQUARTERS,
	"¿":FullKeyList.KEY_QUESTIONDOWN,
	"à":FullKeyList.KEY_AGRAVE,
	"á":FullKeyList.KEY_AACUTE,
	"â":FullKeyList.KEY_ACIRCUMFLEX,
	"ã":FullKeyList.KEY_ATILDE,
	"ä":196,
	"å":FullKeyList.KEY_ARING,
	"æ":FullKeyList.KEY_AE,
	"ç":FullKeyList.KEY_CCEDILLA,
	"è":FullKeyList.KEY_EGRAVE,
	"é":FullKeyList.KEY_EACUTE,
	"ê":FullKeyList.KEY_ECIRCUMFLEX,
	"ë":FullKeyList.KEY_EDIAERESIS,
	"ì":FullKeyList.KEY_IGRAVE,
	"í":FullKeyList.KEY_IACUTE,
	"î":FullKeyList.KEY_ICIRCUMFLEX,
	"Idiaeresis":FullKeyList.KEY_IDIAERESIS,
	"ð":FullKeyList.KEY_ETH,
	"ñ":FullKeyList.KEY_NTILDE,
	"ò":FullKeyList.KEY_OGRAVE,
	"ó":FullKeyList.KEY_OACUTE,
	"ô":FullKeyList.KEY_OCIRCUMFLEX,
	"õ":FullKeyList.KEY_OTILDE,
	"ö":214,
	"×":FullKeyList.KEY_MULTIPLY,
	"ø":FullKeyList.KEY_OOBLIQUE,
	"ù":FullKeyList.KEY_UGRAVE,
	"ú":FullKeyList.KEY_UACUTE,
	"û":FullKeyList.KEY_UCIRCUMFLEX,
	"ü":220,
	"ý":FullKeyList.KEY_YACUTE,
	"þ":FullKeyList.KEY_THORN,
	"ß":FullKeyList.KEY_SSHARP,
	"÷":FullKeyList.KEY_DIVISION,
	"ÿ":FullKeyList.KEY_YDIAERESIS,
}

func hasLowercase(code: int):
	return keyListLowercase.values().has(code)

func getUnicodeFromString(name:String, debug=false)-> int:
	if keyListUnicode.has(str(name)):
		if debug:
			print("Unicode OK:"+name)
		return keyListUnicode.get(str(name))
	else:
		if debug:
			print("Unicode Key not found:"+ name)
		return FullKeyList.KEY_UNKNOWN
